package cav.lscaner.utils;

public interface ConstantManager{

    String SELECTED_FILE = "SELECTED_FILE";
    String DELIMETER_STORE = "DELIMETER_STORE";
    String DELIMETER_SCANER = "DELIMETER_SCANER";
    String SCALE_PREFIX = "SCALE_PREFIX";
    String SCALE_SIZE = "SCALE_SIZE";
    String STORE_FILE_NAME = "STORE_FILE_NAME";
    String SELECTED_FILE_NAME = "SELECTED_FILE_NAME";
    String DEMO_VERSION = "DEMO_VERSION";
    String REGISTRY_NUMBER = "REGISTRY_NUMBER";
    String CODE_FILE = "CODE_FILE";
    String SELECTED_FILE_TYPE = "SELECTED_FILE_TYPE";
    int FILE_TYPE_PRODUCT = 0;
    int FILE_TYPE_EGAIS = 1;

}